Auto download thprac
Co-authored-by: Kauan Decarli <kauandecarli@gmail.com>

diff --git a/thcrap_proton b/thcrap_proton
--- a/thcrap_proton
+++ b/thcrap_proton
@@ -4,6 +4,9 @@
 THCRAP_FOLDER="$XDG_DATA_HOME/thcrap"
 THCRAP_CONFIG=en.js
 
+# This is `thprac` not `thcrap`
+THPRAC_FOLDER="$XDG_DATA_HOME/thprac"
+
 ZENITY=$(which zenity)
 
 echo "" > '/tmp/thcrap_proton.log'
@@ -18,10 +21,10 @@ launch_config() {
     sh -c "$RUN"
 }
 
-while getopts "v c:p:e:" flag; do
+while getopts "vp c:e:" flag; do
     case "${flag}" in
         v) USE_VPATCH=1;;
-        p) THPRAC_EXE=${OPTARG};;
+        p) USE_THPRAC=1;;
         c) THCRAP_CONFIG=${OPTARG};;
         e) COMMAND=${OPTARG};; # Deprecated
     esac
@@ -73,6 +76,32 @@ if [ ! -f "$THCRAP_FOLDER/config/$THCRAP_CONFIG" ]; then
     fi
 fi
 
+if [ "$USE_THPRAC" == 1 ]; then
+    THPRAC_VERSION=$(LD_LIBRARY_PATH=/usr/lib64:/usr/lib curl --connect-timeout 5 -si https://github.com/touhouworldcup/thprac/releases/latest | grep location: | sed 's@.*/@@' | tr -d '[:space:]')
+    if [[ -n "$THPRAC_VERSION" && ! -f "$THPRAC_FOLDER/thprac.$THPRAC_VERSION.exe" ]]; then
+        # Install latest version
+        mkdir -p "$THPRAC_FOLDER"
+        if [ ! -w "$THPRAC_FOLDER" ]; then
+            ${ZENITY} --error --text="The directory \"$THPRAC_FOLDER\" could not be created or is not writable. Check your permissions and try again."
+            exit
+        fi
+        LD_LIBRARY_PATH=/usr/lib64:/usr/lib curl -L -f "https://github.com/touhouworldcup/thprac/releases/download/$THPRAC_VERSION/thprac.$THPRAC_VERSION.exe" -o "$THPRAC_FOLDER/thprac.$THPRAC_VERSION.exe" | ${ZENITY} --progress --pulsate --auto-close --text="Downloading \"thprac.$THPRAC_VERSION.exe\""
+        if [ $? = 0 ]; then
+            # Create a symlink to latest version
+            ln -srf "$THPRAC_FOLDER/thprac.$THPRAC_VERSION.exe" "$THPRAC_FOLDER/thprac.exe"
+            # Remove old versions, only keep the latest version
+            find "$THPRAC_FOLDER" -maxdepth 1 -name "thprac.*.exe" \! -name "thprac.$THPRAC_VERSION.exe" -exec rm {} \;
+        fi
+    fi
+
+    # Make sure thprac is installed
+    if [ ! -f "$THPRAC_FOLDER/thprac.exe" ]; then
+        # no installed version
+        ${ZENITY} --error --text="thprac installation failed. Aborting"
+        exit
+    fi
+fi
+
 TH_REGEX="(th[0-9]+|東方紅魔郷)"
 
 if [ "$USE_VPATCH" == 1 ]; then
@@ -93,11 +122,11 @@ echo "---------------------------------------------------------"
 
 sh -c "$COMMAND" &
 
-if [ -n "$THPRAC_EXE" ]; then
+if [ "$USE_THPRAC" == 1 ]; then
     # wait 5s and launch thprac so it could auto attach to the game
     sleep 5
     PROTON_CMD=$( echo "$COMMAND" | sed -n "s/^.*-- \(.*\) waitforexitandrun.*$/\\1/p" )
-    RUN_THPRAC="$PROTON_CMD run '$THPRAC_EXE'"
+    RUN_THPRAC="$PROTON_CMD run '$THPRAC_FOLDER/thprac.exe'"
     echo "-----------------------THPRAC COMMAND--------------------"
     echo "$RUN_THPRAC"
     echo "---------------------------------------------------------"
